name: chacha
description: An implementation of the ChaCha20 cipher, Poly1305 MAC, and ChaCha20-Poly1305 AEAD as per RFC 8439.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
